[package]
name = "open-gal-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
clap = { version = "3.0.0-beta.4", features = ["yaml"] }
open-gal = { git = "https://github.com/eelias13/open-gal"}
